const ZILLOW_API_KEY = 'd8cb588467msh204401deaab20e0p1ea300jsnc14e4485c448'
const ZILLOW_API_HOST = 'zillow56.p.rapidapi.com'
const GEO_LOCATE_API_KEY = '2oEsMsawruoO/lL4GYMVCg==FeIwqiMyDicp17fH'
const FIREBASE_API_KEY = "AIzaSyBwre-a9D9tE1hJAivnxlcM2gAzeX1ErZk"
const FIREBASE_AUTH_DOMAIN = "rippe-production.firebaseapp.com"
const FIREBASE_PROJECT_ID = "rippe-production"
const FIREBASE_STORAGE_BUCKET = "rippe-production.appspot.com"
const FIREBASE_MESSAGING_SENDER_ID = "774139530269"
const FIREBASE_APP_ID = "1:774139530269:web:15777bc66b975933a0caf4"
const FIREBASE_MEASUREMENT_ID = "G-WYP5W4Z8RL"

module.exports = {
  ZILLOW_API_KEY,
  ZILLOW_API_HOST,
  GEO_LOCATE_API_KEY,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID
}