import { useNavigation } from '@react-navigation/native'
import React, { useContext, useState } from 'react'
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, TextInput, Dimensions, Alert } from 'react-native'
import { Feather } from 'react-native-vector-icons'
import { PropertyContext } from '../../Context/PropertyContext'
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../../Api/firebaseTesting'

const deviceWidth = Dimensions.get('window').width

const OfferScreen = () => {
  const navigation = useNavigation()
  const {property} = useContext(PropertyContext)

  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [phone, setPhone] = useState('')
  const [amount, setAmount] = useState('')
  const [message, setMessage] = useState('')
  const [offerType, setOfferType] = useState('Loan')
  const [preapproved, setPreapproved] = useState('Yes')
  const [bestTime, setBestTime] = useState('Morning')
  const [viewedProperty, setViewedProperty] = useState('Yes')

  const address = property.address.streetAddress + '. ' +
                  property.address.city + ', ' +
                  property.address.state + ' ' +
                  property.address.zipcode

  const submitOffer = () => {
    const subject = 'Property offer - ' + name + ' / ' + address
    const body = 'This is a property offer for ' + address + '. \n' + name + ' is sending the following' + 
                  ' message regarding the property: \n\n' + message + '\n\n Other details: \n Current Type of Offer: ' + 
                  offerType + '. \n Offer Amount: ' + amount + '\n Viewed the property: ' + viewedProperty +
                  '\n Best time to reach out: ' + bestTime + '\n\n Contact Details: \n' + name + 
                  '\nPhone:' + phone + '\n Email: ' + email + '\n\n This email was automatically generated by Rippe. \n\n\n ' + 
                  'Rippe Inc. \nsupport@rippeapp.com \n (949) 403-7179 \n Los Angeles, CA' 
    const collectionRef = collection(db, 'Offers')
    let offerInfo = {}
    offerInfo.streetAddress = property.streetAddress
    offerInfo.city = property.city
    offerInfo.state = property.state
    offerInfo.zipcode = property.zipcode
    offerInfo.fullAddress = address
    offerInfo.price = property.price
    offerInfo.zpid = property.zpid
    offerInfo.name = name 
    offerInfo.email = email 
    offerInfo.phone = phone 
    offerInfo.message = body
    offerInfo.offerType = offerType
    offerInfo.preapproved = preapproved
    offerInfo.bestTime = bestTime
    offerInfo.viewedProperty = viewedProperty
    offerInfo.subject = subject
    addDoc(collectionRef, {
      'property': offerInfo,
      'zpid': property.zpid,
      'createdAt': serverTimestamp()
    })
    .then((response) => {
      alert('Email was sent.')
    })
    .catch((error) => {
      console.error(error)
    })
  }

  const displayPhone = () => {
    return(
      <View style={styles.container}>
        <ScrollView>
          <View style={styles.header}>
            <TouchableOpacity onPress={() => {navigation.goBack()}}>
              <Feather name='chevron-left' size={28}/>
            </TouchableOpacity>
            <Text style={styles.headerText}>Starting An Offer</Text>
          </View>
          <View style={styles.infoContainer}>
            <Text style={styles.info}>
              We are excited that you found an investment property you liked. We want
              to make the process as simple as possible. Fill out the form below and an agent will get in
              contact with you to start the process.
            </Text>
          </View>
          <View style={styles.contactContainer}>
            <View style={styles.groupV}>
              <Text style={styles.label}>Contact Name</Text>
              <TextInput 
                value={name}
                onChangeText={(value) => {setName(value)}}
                style={styles.fullInput}
                placeholder='John Doe'
              />
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Contact Number</Text>
              <TextInput 
                value={phone}
                onChangeText={(value) => {setPhone(value)}}
                style={styles.fullInput}
                placeholder='(123)456-7890'
                keyboardType='numeric'
              />
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Contact Email</Text>
              <TextInput 
                value={email}
                onChangeText={(value) => {setEmail(value)}}
                style={styles.fullInput}
                placeholder='johndoe@gmail.com'
              />
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Offer Amount ($)</Text>
              <TextInput 
                value={amount}
                onChangeText={(value) => {setAmount(value)}}
                style={styles.fullInput}
                keyboardType='numeric'
              />
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Type Of Offer</Text>
                {
                  offerType == 'Cash' ? <View style={styles.options}>
                                            <TouchableOpacity onPress={() => {setOfferType('Cash')}} style={[styles.optionContainer50, styles.blue]}>
                                              <Text style={[styles.label, styles.white]}>Cash</Text>
                                            </TouchableOpacity>
                                            <TouchableOpacity onPress={() => {setOfferType('Loan')}} style={styles.optionContainer50}>
                                              <Text style={styles.label}>Loan</Text>
                                            </TouchableOpacity>
                                          </View>
                                        : <View style={styles.options}>
                                            <TouchableOpacity onPress={() => {setOfferType('Cash')}} style={styles.optionContainer50}>
                                              <Text style={styles.label}>Cash</Text>
                                            </TouchableOpacity>
                                            <TouchableOpacity onPress={() => {setOfferType('Loan')}} style={[styles.optionContainer50, styles.blue]}>
                                              <Text style={[styles.label, styles.white]}>Loan</Text>
                                            </TouchableOpacity>
                                          </View>
                }
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Are You Preapproved</Text>
              {
                preapproved == 'Yes' ? <View style={styles.options}>
                                        <TouchableOpacity onPress={() => {setPreapproved('Yes')}} style={[styles.optionContainer50, styles.blue]}>
                                          <Text style={[styles.label, styles.white]}>Yes</Text>
                                        </TouchableOpacity>
                                        <TouchableOpacity onPress={() => {setPreapproved('No')}} style={styles.optionContainer50}>
                                          <Text style={styles.label}>No</Text>
                                        </TouchableOpacity>
                                      </View>
                                    : <View style={styles.options}>
                                        <TouchableOpacity onPress={() => {setPreapproved('Yes')}} style={styles.optionContainer50}>
                                          <Text style={styles.label}>Yes</Text>
                                        </TouchableOpacity>
                                        <TouchableOpacity onPress={() => {setPreapproved('No')}} style={[styles.optionContainer50, styles.blue]}>
                                          <Text style={[styles.label, styles.white]}>No</Text>
                                        </TouchableOpacity>
                                      </View>
                  }
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Best Time To Contact You</Text>
              {
                bestTime == 'Mornings' ?  <View style={styles.options}>
                                            <TouchableOpacity onPress={() => {setBestTime('Mornings')}} style={[styles.optionContainer33, styles.blue]}>
                                              <Text style={[styles.label, styles.white]}>Mornings</Text>
                                            </TouchableOpacity>
                                            <TouchableOpacity onPress={() => {setBestTime('Afternoons')}} style={styles.optionContainer33}>
                                              <Text style={styles.label}>Afternoons</Text>
                                            </TouchableOpacity>
                                            <TouchableOpacity onPress={() => {setBestTime('Evenings')}} style={styles.optionContainer33}>
                                              <Text style={styles.label}>Evenings</Text>
                                            </TouchableOpacity>
                                          </View>
                                        : bestTime == 'Afternoons' ?  <View style={styles.options}>
                                                                        <TouchableOpacity onPress={() => {setBestTime('Mornings')}} style={styles.optionContainer33}>
                                                                          <Text style={styles.label}>Mornings</Text>
                                                                        </TouchableOpacity>
                                                                        <TouchableOpacity onPress={() => {setBestTime('Afternoons')}} style={[styles.optionContainer33, styles.blue]}>
                                                                          <Text style={[styles.label, styles.white]}>Afternoons</Text>
                                                                        </TouchableOpacity>
                                                                        <TouchableOpacity onPress={() => {setBestTime('Evenings')}} style={styles.optionContainer33}>
                                                                          <Text style={styles.label}>Evenings</Text>
                                                                        </TouchableOpacity>
                                                                      </View>
                                                                    : <View style={styles.options}>
                                                                        <TouchableOpacity onPress={() => {setBestTime('Mornings')}} style={styles.optionContainer33}>
                                                                          <Text style={styles.label}>Mornings</Text>
                                                                        </TouchableOpacity>
                                                                        <TouchableOpacity onPress={() => {setBestTime('Afternoons')}} style={styles.optionContainer33}>
                                                                          <Text style={styles.label}>Afternoons</Text>
                                                                        </TouchableOpacity>
                                                                        <TouchableOpacity onPress={() => {setBestTime('Evenings')}} style={[styles.optionContainer33, styles.blue]}>
                                                                          <Text style={[styles.label, styles.white]}>Evenings</Text>
                                                                        </TouchableOpacity>
                                                                      </View>
              }
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Have You Viewed The Property</Text>
              {
                viewedProperty == 'Yes' ? <View style={styles.options}>
                                            <TouchableOpacity onPress={() => {setViewedProperty('Yes')}} style={[styles.optionContainer50, styles.blue]}>
                                              <Text style={[styles.label, styles.white]}>Yes</Text>
                                            </TouchableOpacity>
                                            <TouchableOpacity onPress={() => {setViewedProperty('No')}} style={styles.optionContainer50}>
                                              <Text style={styles.label}>No</Text>
                                            </TouchableOpacity>
                                          </View>
                                        : <View style={styles.options}>
                                            <TouchableOpacity onPress={() => {setViewedProperty('Yes')}} style={styles.optionContainer50}>
                                              <Text style={styles.label}>Yes</Text>
                                            </TouchableOpacity>
                                            <TouchableOpacity onPress={() => {setViewedProperty('No')}} style={[styles.optionContainer50, styles.blue]}>
                                              <Text style={[styles.label, styles.white]}>No</Text>
                                            </TouchableOpacity>
                                          </View>
              }
            </View>
            <TouchableOpacity onPress={() => {submitOffer(); navigation.goBack()}} style={styles.submitContainer}>
              <Text style={styles.labelWhite}>Submit Offer</Text>
            </TouchableOpacity>
          </View>
        </ScrollView>
      </View>
    )
  }

  const displayTablet = () => {
    return(
      <View style={styles.containerTablet}>
        <ScrollView>
          <View style={styles.header}>
            <TouchableOpacity onPress={() => {navigation.goBack()}}>
              <Feather name='chevron-left' size={28}/>
            </TouchableOpacity>
            <Text style={styles.headerText}>Starting An Offer</Text>
          </View>
          <View style={styles.infoContainer}>
            <Text style={styles.info}>
              We are excited that you found an investment property you liked. We want
              to make the process as simple as possible. Fill out the form below and an agent will get in
              contact with you to start the process.
            </Text>
          </View>
          <View style={styles.contactContainer}>
            <View style={styles.groupV}>
              <Text style={styles.label}>Contact Name</Text>
              <TextInput 
                value={name}
                onChangeText={(value) => {setName(value)}}
                style={styles.fullInput}
                placeholder='John Doe'
              />
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Contact Number</Text>
              <TextInput 
                value={phone}
                onChangeText={(value) => {setPhone(value)}}
                style={styles.fullInput}
                placeholder='(123)456-7890'
                keyboardType='numeric'
              />
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Contact Email</Text>
              <TextInput 
                value={email}
                onChangeText={(value) => {setEmail(value)}}
                style={styles.fullInput}
                placeholder='johndoe@gmail.com'
              />
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Offer Amount ($)</Text>
              <TextInput 
                value={amount}
                onChangeText={(value) => {setAmount(value)}}
                style={styles.fullInput}
                keyboardType='numeric'
              />
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Type Of Offer</Text>
                {
                  offerType == 'Cash' ? <View style={styles.options}>
                                            <TouchableOpacity onPress={() => {setOfferType('Cash')}} style={[styles.optionContainer50, styles.blue]}>
                                              <Text style={[styles.label, styles.white]}>Cash</Text>
                                            </TouchableOpacity>
                                            <TouchableOpacity onPress={() => {setOfferType('Loan')}} style={styles.optionContainer50}>
                                              <Text style={styles.label}>Loan</Text>
                                            </TouchableOpacity>
                                          </View>
                                        : <View style={styles.options}>
                                            <TouchableOpacity onPress={() => {setOfferType('Cash')}} style={styles.optionContainer50}>
                                              <Text style={styles.label}>Cash</Text>
                                            </TouchableOpacity>
                                            <TouchableOpacity onPress={() => {setOfferType('Loan')}} style={[styles.optionContainer50, styles.blue]}>
                                              <Text style={[styles.label, styles.white]}>Loan</Text>
                                            </TouchableOpacity>
                                          </View>
                }
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Are You Preapproved</Text>
              {
                preapproved == 'Yes' ? <View style={styles.options}>
                                        <TouchableOpacity onPress={() => {setPreapproved('Yes')}} style={[styles.optionContainer50, styles.blue]}>
                                          <Text style={[styles.label, styles.white]}>Yes</Text>
                                        </TouchableOpacity>
                                        <TouchableOpacity onPress={() => {setPreapproved('No')}} style={styles.optionContainer50}>
                                          <Text style={styles.label}>No</Text>
                                        </TouchableOpacity>
                                      </View>
                                    : <View style={styles.options}>
                                        <TouchableOpacity onPress={() => {setPreapproved('Yes')}} style={styles.optionContainer50}>
                                          <Text style={styles.label}>Yes</Text>
                                        </TouchableOpacity>
                                        <TouchableOpacity onPress={() => {setPreapproved('No')}} style={[styles.optionContainer50, styles.blue]}>
                                          <Text style={[styles.label, styles.white]}>No</Text>
                                        </TouchableOpacity>
                                      </View>
                  }
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Best Time To Contact You</Text>
              {
                bestTime == 'Mornings' ?  <View style={styles.options}>
                                            <TouchableOpacity onPress={() => {setBestTime('Mornings')}} style={[styles.optionContainer33, styles.blue]}>
                                              <Text style={[styles.label, styles.white]}>Mornings</Text>
                                            </TouchableOpacity>
                                            <TouchableOpacity onPress={() => {setBestTime('Afternoons')}} style={styles.optionContainer33}>
                                              <Text style={styles.label}>Afternoons</Text>
                                            </TouchableOpacity>
                                            <TouchableOpacity onPress={() => {setBestTime('Evenings')}} style={styles.optionContainer33}>
                                              <Text style={styles.label}>Evenings</Text>
                                            </TouchableOpacity>
                                          </View>
                                        : bestTime == 'Afternoons' ?  <View style={styles.options}>
                                                                        <TouchableOpacity onPress={() => {setBestTime('Mornings')}} style={styles.optionContainer33}>
                                                                          <Text style={styles.label}>Mornings</Text>
                                                                        </TouchableOpacity>
                                                                        <TouchableOpacity onPress={() => {setBestTime('Afternoons')}} style={[styles.optionContainer33, styles.blue]}>
                                                                          <Text style={[styles.label, styles.white]}>Afternoons</Text>
                                                                        </TouchableOpacity>
                                                                        <TouchableOpacity onPress={() => {setBestTime('Evenings')}} style={styles.optionContainer33}>
                                                                          <Text style={styles.label}>Evenings</Text>
                                                                        </TouchableOpacity>
                                                                      </View>
                                                                    : <View style={styles.options}>
                                                                        <TouchableOpacity onPress={() => {setBestTime('Mornings')}} style={styles.optionContainer33}>
                                                                          <Text style={styles.label}>Mornings</Text>
                                                                        </TouchableOpacity>
                                                                        <TouchableOpacity onPress={() => {setBestTime('Afternoons')}} style={styles.optionContainer33}>
                                                                          <Text style={styles.label}>Afternoons</Text>
                                                                        </TouchableOpacity>
                                                                        <TouchableOpacity onPress={() => {setBestTime('Evenings')}} style={[styles.optionContainer33, styles.blue]}>
                                                                          <Text style={[styles.label, styles.white]}>Evenings</Text>
                                                                        </TouchableOpacity>
                                                                      </View>
              }
            </View>
            <View style={styles.groupV}>
              <Text style={styles.label}>Have You Viewed The Property</Text>
              {
                viewedProperty == 'Yes' ? <View style={styles.options}>
                                            <TouchableOpacity onPress={() => {setViewedProperty('Yes')}} style={[styles.optionContainer50, styles.blue]}>
                                              <Text style={[styles.label, styles.white]}>Yes</Text>
                                            </TouchableOpacity>
                                            <TouchableOpacity onPress={() => {setViewedProperty('No')}} style={styles.optionContainer50}>
                                              <Text style={styles.label}>No</Text>
                                            </TouchableOpacity>
                                          </View>
                                        : <View style={styles.options}>
                                            <TouchableOpacity onPress={() => {setViewedProperty('Yes')}} style={styles.optionContainer50}>
                                              <Text style={styles.label}>Yes</Text>
                                            </TouchableOpacity>
                                            <TouchableOpacity onPress={() => {setViewedProperty('No')}} style={[styles.optionContainer50, styles.blue]}>
                                              <Text style={[styles.label, styles.white]}>No</Text>
                                            </TouchableOpacity>
                                          </View>
              }
            </View>
            <TouchableOpacity onPress={() => {submitOffer(); navigation.goBack()}} style={styles.submitContainer}>
              <Text style={styles.labelWhite}>Submit Offer</Text>
            </TouchableOpacity>
          </View>
        </ScrollView>
      </View>
    )
  }

  return (
    <>
      {
        deviceWidth >= 500 ? displayTablet() : displayPhone()
      }
    </>
  )
}

const styles = StyleSheet.create({
  container: {
    marginTop: 54
  },
  containerTablet: {
    marginTop: 16
  },
  header: {
    display: 'flex',
    flexDirection: 'row',
    height: 56,
    alignItems: 'center',
    borderBottomWidth: 2,
    paddingHorizontal: 8
  },
  headerText: {
    fontSize: 22,
    fontWeight: '700',
  },
  infoContainer: {
    padding: 8,
  },
  info: {
    textAlign: 'center',
    fontSize: 17
  },
  contactContainer: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    padding: 8
  },
  groupV: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    marginBottom: 8
  },
  groupH: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 8
  },
  label: {
    fontSize: 17,
    fontWeight: '500'
  },
  fullInput: {
    fontSize: 17,
    paddingVertical: 2,
    paddingLeft: 2,
    backgroundColor: 'lightgrey',
    borderBottomWidth: 1,
    borderBottomColor: 'black',
    marginTop: 6
  },
  options: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    borderRadius: 5,
    overflow: 'hidden',
    alignItems: 'center',
    backgroundColor: 'lightgrey',
    marginTop: 8
  },
  optionContainer50: {
    width: '50%',
    paddingVertical: 8,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center'
  },
  optionContainer33: {
    width: '33.33%',
    paddingVertical: 8,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center'
  },
  submitContainer: {
    width: '100%',
    paddingVertical: 16,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: 'blue',
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: 8
  },
  labelWhite: {
    fontSize: 17,
    fontWeight: '500',
    color: 'white'
  },
  blue: {
    backgroundColor: 'blue'
  },
  white: {
    color: 'white'
  }
})

export default OfferScreen